apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  containers:
  - name: mysql-server
    image: mysql:8.0
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: password
    ports:
    - containerPort: 3306
      name: mysql
  - name: mysql-client
    image: mysql:8.0
    command: ["/bin/sh"]
    args: ["-c","while true; do sleep 10;done"]
