apiVersion: v1
kind: Secret
metadata: 
  name: mysql-secret
type: Opaque
stringData:
  mysql-user: testuser
  mysql-passwd: passw0rd
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  containers:
  - name: mysql-server
    image: mysql:8.0
    env:
    - name: MYSQL_RANDOM_ROOT_PASSWORD
      value: "yes"
    - name: MYSQL_DATABASE
      value: "testdb"
    ports:
    - containerPort: 3306
      name: mysql
