apiVersion: v1
kind: Pod
metadata:
  name: springboot-pod
spec:
  containers:
  - name: springboot-app
    #image: nginx
    image: kwonghung/spring-boot-docker-secret:latest
    env:
      - name: SPRING_PROFILES_ACTIVE
        value: k8s
    volumeMounts:
    - name: mysql-pw
      mountPath: "/run/secrets/mysql-secret"
      readOnly: true
    ports:
    - containerPort: 8080
      name: http
  volumes:
  - name: mysql-pw
    secret:
      secretName: mysql-secret
#---
#apiVersion: v1
#kind: Secret
#metadata: 
#  name: mysql-secret1
#  labels:
#    app: mysql
#type: Opaque
#data:
#  mysql-passwd: cGFzc3cwcmQ=
#stringData:
#  mysql-user: testuser

