apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: springboot-app
        image: kwonghung/spring-boot-docker-secret:latest
        ports:
        - containerPort: 8080
